pipeline {
    agent any
    environment {
        PASS = credentials('register-pass')
        TAG = credentials('tag_number')
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                    echo $PWD
                   ./jenkins-pipline/jenkins/mvn.sh  mvn -B -DskipTests clean package
                   ./jenkins-pipline/jenkins/build/build.sh
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                ./jenkins-pipline/jenkins/mvn.sh mvn test
                '''
            }
        }
        stage('push') {
            steps {
                sh '''
                ./jenkins-pipline/jenkins/push+/push.sh
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh './jenkins-pipline/jenkins/deploy/deploy.sh'
            }
        }
    }
}
