pipeline {
    agent any
    environment {
        PASS = credentials('registry-pass')
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                   ./jenkins/mvn.sh  mvn -B -DskipTests clean package
                   ./jenkins/build/build.sh
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                ./jenkins/test/mvn.sh mvn test
                '''
            }
        }
        stage('push') {
            steps {
                sh '''
                ./jenkins/push+/push.sh
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh './jenkins/deploy/deploy.sh'
            }
        }
    }
}
